Fix migration when enabling the add-on in Blender 5.1
What: explicitly specifies the execution context when calling migrate_hubs_components during the registration of the add-on in the middle of a session instead of relying on the execution context being passed automatically.

Why: Blender 5.1 now requires the execution context to be specified as well if you want to push an undo step when calling an operator.  Blender 5.1 no longer auto-detects which option you specified if you only specify one and assumes that you are specifying the execution context.  If you try to only specify whether to push an undo step without specifying the execution context, it fails with the following error:

```
Traceback (most recent call last):
    File "/path/to/io_hubs_addon/__init__.py", line 67, in registration_migration
    bpy.ops.wm.migrate_hubs_components(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        True, is_registration=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _bpy.ops.call() argument 3 must be str, not bool
```

Notes:

The change in behaviour is potentially because of the Python upgrade from 3.11 to 3.13, but this specific change (with regard to calling operators) is unreported in the 5.1 release notes.

The specified execution context is the default execution context for operators (so it should be the same as what was automatically passed previously).

Previous versions of Blender shouldn't be affected because both positional options have always been present in this order.

Blender 3.6 and previous also had an option to override the context as the first positional argument (which isn't specified here), but not specifying this shouldn't be a problem as it should just detect which options we're passing.